//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

#pragma warning disable 108 // Disable "CS0108 '{derivedDto}.ToJson()' hides inherited member '{dtoBase}.ToJson()'. Use the new keyword if hiding was intended."
#pragma warning disable 114 // Disable "CS0114 '{derivedDto}.RaisePropertyChanged(String)' hides inherited member 'dtoBase.RaisePropertyChanged(String)'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword."
#pragma warning disable 472 // Disable "CS0472 The result of the expression is always 'false' since a value of type 'Int32' is never equal to 'null' of type 'Int32?'
#pragma warning disable 612 // Disable "CS0612 '...' is obsolete"
#pragma warning disable 649 // Disable "CS0649 Field is never assigned to, and will always have its default value null"
#pragma warning disable 1573 // Disable "CS1573 Parameter '...' has no matching param tag in the XML comment for ...
#pragma warning disable 1591 // Disable "CS1591 Missing XML comment for publicly visible type or member ..."
#pragma warning disable 8073 // Disable "CS8073 The result of the expression is always 'false' since a value of type 'T' is never equal to 'null' of type 'T?'"
#pragma warning disable 3016 // Disable "CS3016 Arrays as attribute arguments is not CLS-compliant"
#pragma warning disable 8600 // Disable "CS8600 Converting null literal or possible null value to non-nullable type"
#pragma warning disable 8602 // Disable "CS8602 Dereference of a possibly null reference"
#pragma warning disable 8603 // Disable "CS8603 Possible null reference return"
#pragma warning disable 8604 // Disable "CS8604 Possible null reference argument for parameter"
#pragma warning disable 8625 // Disable "CS8625 Cannot convert null literal to non-nullable reference type"
#pragma warning disable 8765 // Disable "CS8765 Nullability of type of parameter doesn't match overridden member (possibly because of nullability attributes)."

namespace ApiGateway.Controllers
{
    using System = global::System;

    [System.CodeDom.Compiler.GeneratedCode("NSwag", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public interface IAuthenticationController
    {

        /// <summary>
        /// Authenticate a user
        /// </summary>


        /// <returns>JWT generated successfully</returns>

        System.Threading.Tasks.Task<LoginResponse> LoginAsync(LoginRequest body);

    }

    [System.CodeDom.Compiler.GeneratedCode("NSwag", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class AuthenticationController : Microsoft.AspNetCore.Mvc.ControllerBase
    {
        private IAuthenticationController _implementation;

        public AuthenticationController(IAuthenticationController implementation)
        {
            _implementation = implementation;
        }

        /// <summary>
        /// Authenticate a user
        /// </summary>
        /// <returns>JWT generated successfully</returns>
        [Microsoft.AspNetCore.Mvc.HttpPost, Microsoft.AspNetCore.Mvc.Route("auth/login")]
        public System.Threading.Tasks.Task<LoginResponse> Login([Microsoft.AspNetCore.Mvc.FromBody] LoginRequest body)
        {

            return _implementation.LoginAsync(body);
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NSwag", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public interface IUsersController
    {

        /// <summary>
        /// List users
        /// </summary>


        /// <returns>Paged users</returns>

        System.Threading.Tasks.Task<UserPagedResponse> GetUsersAsync(int page, int limit);

        /// <summary>
        /// Create user
        /// </summary>


        /// <returns>User created</returns>

        System.Threading.Tasks.Task<UserResponse> CreateUserAsync(CreateUserRequest body);

        /// <summary>
        /// Get user by id
        /// </summary>


        /// <returns>User found</returns>

        System.Threading.Tasks.Task<UserResponse> GetUserAsync(System.Guid id);

    }

    [System.CodeDom.Compiler.GeneratedCode("NSwag", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class UsersController : Microsoft.AspNetCore.Mvc.ControllerBase
    {
        private IUsersController _implementation;

        public UsersController(IUsersController implementation)
        {
            _implementation = implementation;
        }

        /// <summary>
        /// List users
        /// </summary>
        /// <returns>Paged users</returns>
        [Microsoft.AspNetCore.Mvc.HttpGet, Microsoft.AspNetCore.Mvc.Route("users")]
        public System.Threading.Tasks.Task<UserPagedResponse> GetUsers([Microsoft.AspNetCore.Mvc.FromQuery] int? page, [Microsoft.AspNetCore.Mvc.FromQuery] int? limit)
        {

            return _implementation.GetUsersAsync(page ?? 1, limit ?? 10);
        }

        /// <summary>
        /// Create user
        /// </summary>
        /// <returns>User created</returns>
        [Microsoft.AspNetCore.Mvc.HttpPost, Microsoft.AspNetCore.Mvc.Route("users")]
        public System.Threading.Tasks.Task<UserResponse> CreateUser([Microsoft.AspNetCore.Mvc.FromBody] CreateUserRequest body)
        {

            return _implementation.CreateUserAsync(body);
        }

        /// <summary>
        /// Get user by id
        /// </summary>
        /// <returns>User found</returns>
        [Microsoft.AspNetCore.Mvc.HttpGet, Microsoft.AspNetCore.Mvc.Route("users/{id}")]
        public System.Threading.Tasks.Task<UserResponse> GetUser(System.Guid id)
        {

            return _implementation.GetUserAsync(id);
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NSwag", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public interface IEmployeesController
    {

        /// <summary>
        /// Returns all employees
        /// </summary>

        /// <param name="page">Page number you wish to consult.</param>

        /// <param name="limit">Maximum number of items per page.</param>

        /// <returns>Employee list returned successfully</returns>

        System.Threading.Tasks.Task<EmployeeResponse> GetEmployeesAsync(int page, int limit);

        /// <summary>
        /// Creates a new employee
        /// </summary>

        /// <returns>Employee created</returns>

        System.Threading.Tasks.Task CreateEmployeeAsync();

        /// <summary>
        /// Returns an employee by ID
        /// </summary>


        /// <returns>Employee found</returns>

        System.Threading.Tasks.Task GetEmployeeAsync(double id);

        /// <summary>
        /// Updates an employee
        /// </summary>


        /// <returns>Employee updated</returns>

        System.Threading.Tasks.Task UpdateEmployeeAsync(double id);

        /// <summary>
        /// Deletes an employee
        /// </summary>


        /// <returns>Employee deleted</returns>

        System.Threading.Tasks.Task DeleteEmployeeAsync(double id);

    }

    [System.CodeDom.Compiler.GeneratedCode("NSwag", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class EmployeesController : Microsoft.AspNetCore.Mvc.ControllerBase
    {
        private IEmployeesController _implementation;

        public EmployeesController(IEmployeesController implementation)
        {
            _implementation = implementation;
        }

        /// <summary>
        /// Returns all employees
        /// </summary>
        /// <param name="page">Page number you wish to consult.</param>
        /// <param name="limit">Maximum number of items per page.</param>
        /// <returns>Employee list returned successfully</returns>
        [Microsoft.AspNetCore.Mvc.HttpGet, Microsoft.AspNetCore.Mvc.Route("api/employees")]
        public System.Threading.Tasks.Task<EmployeeResponse> GetEmployees([Microsoft.AspNetCore.Mvc.FromQuery] int? page, [Microsoft.AspNetCore.Mvc.FromQuery] int? limit)
        {

            return _implementation.GetEmployeesAsync(page ?? 1, limit ?? 10);
        }

        /// <summary>
        /// Creates a new employee
        /// </summary>
        /// <returns>Employee created</returns>
        [Microsoft.AspNetCore.Mvc.HttpPost, Microsoft.AspNetCore.Mvc.Route("api/employees")]
        public System.Threading.Tasks.Task CreateEmployee()
        {

            return _implementation.CreateEmployeeAsync();
        }

        /// <summary>
        /// Returns an employee by ID
        /// </summary>
        /// <returns>Employee found</returns>
        [Microsoft.AspNetCore.Mvc.HttpGet, Microsoft.AspNetCore.Mvc.Route("api/employees/{id}")]
        public System.Threading.Tasks.Task GetEmployee(double id)
        {

            return _implementation.GetEmployeeAsync(id);
        }

        /// <summary>
        /// Updates an employee
        /// </summary>
        /// <returns>Employee updated</returns>
        [Microsoft.AspNetCore.Mvc.HttpPut, Microsoft.AspNetCore.Mvc.Route("api/employees/{id}")]
        public System.Threading.Tasks.Task UpdateEmployee(double id)
        {

            return _implementation.UpdateEmployeeAsync(id);
        }

        /// <summary>
        /// Deletes an employee
        /// </summary>
        /// <returns>Employee deleted</returns>
        [Microsoft.AspNetCore.Mvc.HttpDelete, Microsoft.AspNetCore.Mvc.Route("api/employees/{id}")]
        public System.Threading.Tasks.Task DeleteEmployee(double id)
        {

            return _implementation.DeleteEmployeeAsync(id);
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class LoginRequest
    {

        [System.Text.Json.Serialization.JsonPropertyName("username")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string Username { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("password")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string Password { get; set; }

        private System.Collections.Generic.IDictionary<string, object> _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class LoginResponse
    {

        [System.Text.Json.Serialization.JsonPropertyName("accessToken")]
        public string AccessToken { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("expiresIn")]
        public int ExpiresIn { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("tokenType")]
        public string TokenType { get; set; }

        private System.Collections.Generic.IDictionary<string, object> _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class UserResponse
    {

        /// <summary>
        /// Unique identifier of the user.
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("id")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public System.Guid Id { get; set; }

        /// <summary>
        /// User login name.
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("username")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string Username { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("role")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        [System.Text.Json.Serialization.JsonConverter(typeof(System.Text.Json.Serialization.JsonStringEnumConverter<Role>))]
        public Role Role { get; set; }

        private System.Collections.Generic.IDictionary<string, object> _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class UserPagedResponse
    {

        [System.Text.Json.Serialization.JsonPropertyName("items")]
        [System.ComponentModel.DataAnnotations.Required]
        public System.Collections.Generic.List<UserResponse> Items { get; set; } = new System.Collections.Generic.List<UserResponse>();

        [System.Text.Json.Serialization.JsonPropertyName("total")]
        public int Total { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("page")]
        public int Page { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("limit")]
        public int Limit { get; set; }

        private System.Collections.Generic.IDictionary<string, object> _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class CreateUserRequest
    {

        [System.Text.Json.Serialization.JsonPropertyName("username")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string Username { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("password")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string Password { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("role")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        [System.Text.Json.Serialization.JsonConverter(typeof(System.Text.Json.Serialization.JsonStringEnumConverter<Role>))]
        public Role Role { get; set; }

        private System.Collections.Generic.IDictionary<string, object> _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public enum Role
    {

        [System.Runtime.Serialization.EnumMember(Value = @"Admin")]
        Admin = 0,

        [System.Runtime.Serialization.EnumMember(Value = @"Employee.Read")]
        Employee_Read = 1,

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class EmployeeResponse
    {

        [System.Text.Json.Serialization.JsonPropertyName("employees")]
        public System.Collections.Generic.List<Employee> Employees { get; set; }

        private System.Collections.Generic.IDictionary<string, object> _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class Employee
    {

        /// <summary>
        /// Unique identifier for the employee
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("id")]
        public double Id { get; set; }

        /// <summary>
        /// Full name of the employee
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("name")]
        public string Name { get; set; }

        /// <summary>
        /// Job position of the employee
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("position")]
        public string Position { get; set; }

        /// <summary>
        /// Salary of the employee
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("salary")]
        public float Salary { get; set; }

        private System.Collections.Generic.IDictionary<string, object> _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }


}

#pragma warning restore  108
#pragma warning restore  114
#pragma warning restore  472
#pragma warning restore  612
#pragma warning restore  649
#pragma warning restore 1573
#pragma warning restore 1591
#pragma warning restore 8073
#pragma warning restore 3016
#pragma warning restore 8600
#pragma warning restore 8602
#pragma warning restore 8603
#pragma warning restore 8604
#pragma warning restore 8625
#pragma warning restore 8765